[package]
name = "rush"
version = "1.1.0"
edition = "2021"
description = "rush: a zero-dependency Rust implementation of ush, remote terminal over websockets, for Linux and Windows."
license = "MIT"

[[bin]]
name = "rush"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
